package com.fourleafclover.tarot.constant

const val TAROT_1 = "THE MAGICIAN"
const val TAROT_2 = "THE HIGH PRIESTESS"
const val TAROT_3 = "THE EMPRESS"
const val TAROT_4 = "THE EMPEROR"
const val TAROT_5 = "THE POPE"
const val TAROT_6 = "THE LOVERS"
const val TAROT_7 = "THE CHARIOT"
const val TAROT_8 = "THE FORSE"
const val TAROT_9 = "THE HERMIT"
const val TAROT_10 = "THE WHEEL OF FORTUNE"
const val TAROT_11 = "THE JUSTICE"
const val TAROT_12 = "THE HANGED MAN"
const val TAROT_13 = "THE DEATH"
const val TAROT_14 = "THE TEMPERANCE"
const val TAROT_15 = "THE DEVIL"
const val TAROT_16 = "THE TOWER"
const val TAROT_17 = "THE STAR"
const val TAROT_18 = "THE MOON"
const val TAROT_19 = "THE SUN"
const val TAROT_20 = "THE JUDGEMENT"
const val TAROT_21 = "THE WORLD"

