package com.fourleafclover.tarot.constant

// 임시로 상수 사용
const val loveFortune = "연애운"
const val studyFortune = "학업운"
const val dreamFortune = "소망운"
const val jobFortune = "직업운"
const val todayFortune = "오늘의 운세"

const val loveMajorQuestion = "그 사람의 마음은?"
const val studyMajorQuestion = "시험 결과가 궁금해!"
const val dreamMajorQuestion = "꿈이 이뤄졌으면!"
const val jobMajorQuestion = "취업할 수 있을까?"
const val todayMajorQuestion = "나의 하루가 궁금해!"

const val loveSubQuestion1 = "그 사람과의 첫만남은 어땠나요?"
const val loveSubQuestion2 = "그 사람에 대한 현재 나의 감정은?"
const val loveSubQuestion3 = "그 사람과 어떤 관계가 되고 싶나요?"
const val studySubQuestion1 = "어떤 시험을 준비하고 있나요?"
const val studySubQuestion2 = "시험을 위해 어떤 노력을 하고 있나요?"
const val studySubQuestion3 = "시험에서 어떤 결과를 얻고 싶나요?"
const val dreamSubQuestion1 = "이루고 싶은 꿈이 무엇인가요?"
const val dreamSubQuestion2 = "그 꿈을 위해 어떤 노력을 하고 있나요?"
const val dreamSubQuestion3 = "꿈을 이루는데 있어 가장 장애물이 되는 것이 무엇인가요?"
const val jobSubQuestion1 = "어떤 직무 취업을 준비하고 있나요?"
const val jobSubQuestion2 = "취업을 위해 어떤 노력을 하고 있나요?"
const val jobSubQuestion3 = "취업 준비 중에 어떤 부분이 가장 어려운가요?"

const val lovePlaceHolder1 = "대학교 동아리에서 다정하게 챙겨주는 모습을 보고 반해버렸습니다."
const val lovePlaceHolder2 = "그 사람이 너무 좋아서 생각만 해도 심장이 빨리 뛰는것 같아요."
const val lovePlaceHolder3 = "서로 죽고 못사는 애인 관계가 되고 싶어요."
const val studyPlaceHolder1 = "대학원 졸업 시험을 준비하고 있습니다."
const val studyPlaceHolder2 = "매일 독서실에서 8시간씩 공부를 하고 있습니다."
const val studyPlaceHolder3 = "졸업 시험에 통과해서, 무사히 대학원을 졸업하고 싶습니다."
const val dreamPlaceHolder1 = "30살이 되기 전에 세계 일주를 하고 싶습니다."
const val dreamPlaceHolder2 = "관심이 있는 나라별 여행 정보를 개인 블로그에 꾸준히 모으고 있습니다."
const val dreamPlaceHolder3 = "회사가 항상 바빠서 장기 여행 일정을 잡는 것이 힘듭니다."
const val jobPlaceHolder1 = "IT회사 개발 직무 취업을 준비하고 있습니다."
const val jobPlaceHolder2 = "분기별로 부트캠프에 참여하여 개발 역량을 키우고 있고, 주 1회 개발 스터디를 하고 있습니다."
const val jobPlaceHolder3 = "회사별 코딩테스트를 짧은 기간 안에 준비하는것이 가장 어렵습니다."
